from graphics import *
class shuffle():
    def get1(self,win):
        circ1 = Circle(Point(250,250),3)
        circ1.setFill('black')
        circ1.draw(win)
        text = Text(Point(250,40),'1')
        text.setSize(28)
        text.setFill('red')
        text.draw(win)

    def get2(self,win):
        circ1 = Circle(Point(242,250),3)
        circ1.setFill('black')
        circ2 = Circle(Point(258,250),3)
        circ2.setFill('black')

        circ1.draw(win)
        circ2.draw(win)
        text = Text(Point(250,40),'2')
        text.setSize(28)
        text.setFill('red')
        text.draw(win)
    
    def get3(self,win):
        circ1 = Circle(Point(240,240),2.5)
        circ1.setFill('black')
        circ2 = Circle(Point(250,250),2.5)
        circ2.setFill('black')
        circ3 = Text(Point(260,260),2.5)
        circ3.setFill('black')

        circ1.draw(win)
        circ2.draw(win)
        circ3.draw(win)

        text = Text(Point(250,40),'3')
        text.setSize(28)
        text.setFill('red')
        text.draw(win)

    def get4(self,win):
        circ1 = Circle(Point(242,242),2.5)
        circ1.setFill('black')
        circ2 = Circle(Point(258,242),2.5)
        circ2.setFill('black')
        circ3 = Circle(Point(242,258),2.5)
        circ3.setFill('black')
        circ4 = Circle(Point(259,258),2.5)
        circ4.setFill('black')
        circ1.draw(win)
        circ2.draw(win)
        circ3.draw(win)
        circ4.draw(win)
        text = Text(Point(250,40),'4')
        text.setSize(28)
        text.setFill('red')
        text.draw(win)

    def get5(self,win):
        circ1 = Circle(Point(241,241),2.5)
        circ1.setFill('black')
        circ2 = Circle(Point(259,241),2.5)
        circ2.setFill('black')
        circ3 = Circle(Point(241,259),2.5)
        circ3.setfill('black')
        circ4 = Circle(Point(259,259),2.5)
        circ4.setFill('black')
        circ5 = Circle(Point(250,250),2.5)
        circ5.setFill('black')

        circ1.draw(win)
        circ2.draw(win)
        circ3.draw(win)
        circ4.draw(win)
        circ5.draw(win)
        text = Text(Point(250,40),'5')
        text.setSize(28)
        text.setFill('red')
        text.draw(win)
    
    def get6(self,win):
        circ1 = Circle(Point(240,242),2.5)
        circ1.setFill('black')
        circ2 = Circle(Point(250,242),2.5)
        circ2.setFill('black')
        circ3 = Circle(Point(260,242),2.5)
        circ3.setfill('black')
        circ4 = Circle(Point(240,257),2.5)
        circ4.setFill('black')
        circ5 = Circle(Point(250,257),2.5)
        circ5.setFill('black')
        circ6 = Circle(Point(260,257),2.5)
        circ6.setFill('black')

        circ1.draw(win)
        circ2.draw(win)
        circ3.draw(win)
        circ4.draw(win)
        circ5.draw(win)
        circ6.draw(win)
        text = Text(Point(250,40),'6')
        text.setSize(28)
        text.setFill('red')
        text.draw(win)
    
